import json
import os
import re
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCREENS = os.path.join(ROOT, "assets", "images", "screens")
OUT_JS = os.path.join(ROOT, "assets", "js", "tutorial-data.js")
COPY_JSON = os.path.join(ROOT, "scripts", "screen-copy.json")
DEFAULT_SOURCE = os.path.join(os.path.dirname(ROOT), "All ClassTrack Screens")

ROLES = {
    "student": {"folder": "Student Screen demo", "label": "Student App", "color": "#1F4E96"},
    "faculty": {"folder": "Faculty Screen demo", "label": "Faculty & T.A.", "color": "#F47920"},
    "admin": {"folder": "Admin Screen demo", "label": "Admin Portal", "color": "#15376b", "platform": "desktop"},
}


def sort_key(name):
    match = re.search(r"^[SFA]_(\d+)", name, re.I)
    if match:
        return (0, int(match.group(1)))
    return (1, name.lower())


def load_screen_copy():
    with open(COPY_JSON, encoding="utf-8") as fp:
        return json.load(fp)


def copy_role_images(role, source_root, folder_name):
    src = os.path.join(source_root, folder_name)
    dst = os.path.join(SCREENS, role)
    os.makedirs(dst, exist_ok=True)
    files = sorted(
        [f for f in os.listdir(src) if f.lower().endswith((".jpeg", ".jpg", ".png"))],
        key=sort_key,
    )
    for i, fname in enumerate(files, 1):
        shutil.copy2(os.path.join(src, fname), os.path.join(dst, f"{role}-{i:02d}.jpg"))
    for leftover in os.listdir(dst):
        if leftover.startswith(f"{role}-") and leftover.endswith(".jpg"):
            num = leftover[len(role) + 1 : -4]
            if not num.isdigit() or int(num) > len(files):
                os.remove(os.path.join(dst, leftover))
    return len(files)


def build_steps(role, count, copy_by_role):
    label = role.capitalize()
    meta = {item["screen"]: item for item in copy_by_role.get(role, [])}
    steps = []
    for i in range(1, count + 1):
        item = meta.get(i)
        if item:
            steps.append({"screen": i, "title": item["title"], "desc": item["desc"], "tags": item["tags"]})
        else:
            steps.append({
                "screen": i,
                "title": f"{label} Screen {i}",
                "desc": f"{label} interface - screen {i} from the ClassTrack system.",
                "tags": [label, "UI"],
            })
    return steps


def format_step(step):
    title = step["title"].replace('"', '\\"')
    desc = step["desc"].replace('"', '\\"')
    tags = json.dumps(step["tags"])
    return f'      {{ screen: {step["screen"]}, title: "{title}", desc: "{desc}", tags: {tags} }}'


def main():
    source_root = os.environ.get("CLASSTRACK_SCREENS", DEFAULT_SOURCE)
    if not os.path.isdir(source_root):
        raise SystemExit(f"Screen source not found: {source_root}")

    copy_by_role = load_screen_copy()
    tutorial = {}
    totals = {}

    for role, cfg in ROLES.items():
        count = copy_role_images(role, source_root, cfg["folder"])
        totals[role] = count
        if len(copy_by_role.get(role, [])) != count:
            print(f"warning: {role} copy count mismatch (images={count})")
        tutorial[role] = {
            "label": cfg["label"],
            "color": cfg["color"],
            "steps": build_steps(role, count, copy_by_role),
        }
        if cfg.get("platform"):
            tutorial[role]["platform"] = cfg["platform"]
        print(f"{role}: {count} screens")

    lines = [
        "/* ClassTrack tutorial data - generated by scripts/build-tutorial-data.py */",
        "window.CLASSTRACK_TUTORIAL = {",
    ]
    for role, data in tutorial.items():
        lines.append(f"  {role}: {{")
        lines.append(f'    label: "{data["label"]}",')
        lines.append(f'    color: "{data["color"]}",')
        if data.get("platform"):
            lines.append(f'    platform: "{data["platform"]}",')
        lines.append("    steps: [")
        lines.append(",\n".join(format_step(s) for s in data["steps"]))
        lines.append("    ]")
        lines.append("  },")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("};")
    lines.append("")

    with open(OUT_JS, "w", encoding="utf-8") as fp:
        fp.write("\n".join(lines))

    print("Wrote", OUT_JS)
    print("Totals:", totals, "Grand:", sum(totals.values()))


if __name__ == "__main__":
    main()
